#!/bin/bash

# Store the Dotfiles Directory Location
DOTLOC="${BASH_SOURCE%/*}"
if [[ ! -d "$DOTLOC" ]]; then DOTLOC="$PWD"; fi
ABSDOTLOC="${HOME}/${DOTLOC}"

# Create Vim Folder Link
VIMLINK="${DOTLOC}/links/vim"
if [ -L $VIMLINK ]; then rm $VIMLINK; fi
ln -s "${ABSDOTLOC}/vim" $VIMLINK
unset -v VIMLINK

# Create Symlinks for all Dotfiles
DOTFILES="${DOTLOC}/links/*"
for D in $DOTFILES; do
  HOMEFILE="${HOME}/.${D##*/}"
  if [ -L $HOMEFILE ]; then
    # If the existing dotfile is a symlink
    # Remove it
    rm $HOMEFILE
  elif [[ -f $HOMEFILE || -d $HOMEFILE ]]; then
    BKP="${HOME}/.bkp"
    if [[ ! -d $BKP ]]; then mkdir $BKP; fi
    # If the existing dotfile is a file or directory
    # Move it to backup folder
    mv $HOMEFILE "${BKP}/"
    unset -v BKP
  fi
  # Create symlink
  ln -s $D $HOMEFILE
  unset -v HOMEFILE
done
unset -v DOTFILES

# Load up the .bashrc
source $HOME/.bashrc

# Additional ViM setup
git clone https://github.com/gmarik/Vundle.vim.git "${DOTLOC}/vim/bundle/Vundle.vim"
# Install the plugins
vim +PluginInstall +qall
# Linkup the colors/ folder
COLORSLINK="${DOTLOC}/vim/colors"
if [ -L $COLORSLINK ]; then rm $COLORSLINK; fi
ln -s "${ABSDOTLOC}/vim/bundle/vim-colorschemes/colors" $COLORSLINK
unset -v COLORSLINK
# Install fonts
bash $DOTLOC/vim/bundle/fonts/install.sh
echo "Refreshing the font cache..."
sudo fc-cache -fv
echo "Font cache refresh complete :)"
