#!/bin/bash
TARGET_LOC=$HOME

function symlink-dotfile () {
  TARGET_FILE="${TARGET_LOC}/.${1##*/}"

  if [ -L $TARGET_FILE ]; then
    # If the existing dotfile is a symlink
    # Remove it
    rm $TARGET_FILE

  elif [[ -f $TARGET_FILE || -d $TARGET_FILE ]]; then
    BKP="${TARGET_LOC}/.dotfiles-bkp"
    if [[ ! -d $BKP ]]; then mkdir $BKP; fi
    # If the existing dotfile is a file or directory
    # Move it to backup folder
    mv $TARGET_FILE "${BKP}/"
    unset -v BKP
  fi
  # Create symlink
  ln -s "$1" $TARGET_FILE
}

# Store the Dotfiles Directory Location
DOTLOC="${BASH_SOURCE%/*}"
if [[ ! -d "$DOTLOC" ]]; then DOTLOC="$PWD"; fi

# Create Symlinks for all Dotfiles
DOTFILES="${DOTLOC}/links/*"
for FILE in $DOTFILES; do symlink-dotfile $FILE; done
unset -v DOTFILES

# Load up the .bashrc
source $TARGET_LOC/.bashrc

# Create Vim Folder Link
symlink-dotfile "${DOTLOC}/vim"

# Additional ViM setup
VIM_LOC="${TARGET_LOC}/.vim"
git clone https://github.com/gmarik/Vundle.vim.git "${VIM_LOC}/bundle/vundle"
# Install the plugins
vim "+silent PluginInstall" "+silent qall"
# Linkup the colors/ folder
COLORSLINK="${VIM_LOC}/colors"
if [ -L $COLORSLINK ]; then rm $COLORSLINK; fi
ln -s "${VIM_LOC}/bundle/vim-colorschemes/colors" $COLORSLINK
unset -v COLORSLINK VIM_LOC
# Install fonts
bash $VIMLINK/bundle/fonts/install.sh
echo "Refreshing the font cache..."
sudo fc-cache -fv
echo "Font cache refresh complete :)"
