#!/bin/bash

# This is the main bash file to be symlinked as .bashrc

# If not running interactively, don't do anything
# case $- in
#     *i*) ;;
#       *) return;;
# esac
# 
# Store actual location as reference for includes
BASHLOC=$(readlink $BASH_SOURCE); BASHLOC="${BASHLOC%links/*}bash"
if [[ ! -d "$BASHLOC" ]]; then BASHLOC="$PWD"; fi

# Include all configuration files
CONFIGS="${BASHLOC}/config/*"
for C in $CONFIGS; do
  if [ -f "${C}" ]; then
    . "${C}"
  fi
done
unset -v CONFIGS

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
