#!/bin/bash

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# List (ls) aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# File system traversal
alias ..='cd ../'
alias ...='cd ../../'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# System tasks
alias bp='vim ~/.bash_profile &'
alias refresh='source ~/.bash_profile; reset'
alias colours='bash $BASHLOC/scripts/colors'

# Development tasks
source $BASHLOC/scripts/git-bash-completion
alias g="git"
function vx {
  # SSH into running Vagrant Box and execute passed command
  # Connection closed immediately after execution
  # All output of the command can be seen as if it were ran locally
  eval 'vagrant ssh -c '"'cd /vagrant/; "$*"'"
}


# Search functions
alias findme='grep -nir --exclude=\*.svn\* --exclude=\*.swp'
alias whouses='grep -lir --exclude=\*.svn\* --exclude=\*.swp'
alias findfile='find . -iname'
alias inspect='du -csh'

# Reference
alias chmodref='bash $BASHLOC/scripts/chmod'

# MP3 Editing
alias mp3info='bash $BASHLOC/scripts/mp3'

# Editors
alias pycharm='/opt/pycharm/pycharm-2016.3.2/bin/pycharm.sh'

# Mediaware
SPLICE_DIR=$HOME/src/splice
SPLICER2SERVER_DIR=$SPLICE_DIR/application/splicer2server
SPLICER_BUILD_DIR=$SPLICER2SERVER_DIR/build/xenial_testing/release64
# alias splice_webui='python webui.py '
alias splice_build='cd $SPLICER_BUILD_DIR; remedy $SPLICE_DIR/src.remedy splicer2server_webui'
alias splice_run='python $SPLICER2SERVER_DIR/webui/webui.py $SPLICER2SERVER_DIR/splicer2server_app/config/splicer2server_config.xml $SPLICER2SERVER_DIR/webui/ascp/autosvr.xml --port 8080'
alias splice_run_old='cd $SPLICER2SERVER_DIR/webui; python webui.py --port 8080'
alias splice='splice_build && splice_run'
alias dns-vpn='sudo cp /etc/resolv.conf.vpn /etc/resolv.conf'
alias dns-local='sudo rm /etc/resolv.conf && sudo ln -s /run/resolvconf/resolv.conf /etc/resolv.conf'

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi
