#!/bin/bash

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# List (ls) aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# File system traversal
alias ..='cd ../'
alias ...='cd ../../'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# System tasks
alias bp='vim ~/.bash_profile &'
alias refresh='source ~/.bash_profile; reset'
alias colours='bash $BASHLOC/scripts/colors'

# Development tasks
source $BASHLOC/scripts/git-bash-completion
alias g="git"
function vx {
  # SSH into running Vagrant Box and execute passed command
  # Connection closed immediately after execution
  # All output of the command can be seen as if it were ran locally
  eval 'vagrant ssh -c '"'cd /vagrant/; "$*"'"
}

# Virtualbox
alias setup-vm='bash $BASHLOC/scripts/virtualbox'

# Search functions
alias findme='grep -nir --exclude=\*.svn\* --exclude=\*.swp'
alias whouses='grep -lir --exclude=\*.svn\* --exclude=\*.swp'
alias findfile='find . -iname'
alias inspect='du -csh'

# Reference
alias chmodref='bash $BASHLOC/scripts/chmod'

# MP3 Editing
alias mp3info='bash $BASHLOC/scripts/mp3'
