#!/bin/bash

# Common working paths
# export PATH="/usr/local/bin:/usr/local/sbin:$PATH:~/bin"

# Make ViM the default terminal editor
export EDITOR=vim

# Load NVM
# https://github.com/creationix/nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion
nvm use node
