#!/bin/bash

# Common working paths
export PATH="/usr/local/bin:/usr/local/sbin:$PATH:~/bin"

# Make ViM the default terminal editor
export EDITOR=vim

# Load NVM
# https://github.com/creationix/nvm#git-install
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
