#!/bin/bash
#
#   This file echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all nine background 
#   colors (default + 8 escapes).
#

T='gYw'   # The test text

function index_colours_fg {
  for i in {0..255}; do
    echo -e "\033[38;05;${i}m${i}"
  done | column -c 320
  echo -e "\033[m"
}

function index_colours_bg {

  for i in {0..255}; do
    pad=' '
    if [[ i -lt 100 && i -gt 9 ]]; then
      pad='  '
    elif [[ i -lt 10 ]]; then
      pad='   '
    fi

    echo -e " \033[48;05;${i}m$pad${i} \033[0m"
  done | column -c 520
  echo -e "\033[m"
}


function theme_colours {
  echo -e "\n                 40m     41m     42m     43m\
     44m     45m     46m     47m";

  for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
           '  36m' '1;36m' '  37m' '1;37m'; do
    FG=${FGs// /}
    echo -en " $FGs \033[$FG  $T  "
    for BG in 40m 41m 42m 43m 44m 45m 46m 47m; do
      echo -en " \033[$FG\033[$BG  $T  \033[0m"
    done
    echo
  done
  echo
}

if [ $# -gt 0 ]; then
  while getopts "ibT:" opt; do
    echo $OPTARG
    case $opt in
      i)
        index_colours_fg
        ;;
      b)
        index_colours_bg
        ;;
      T)
        T="$OPTARG"
        theme_colours
        ;;
    esac
  done
else
  theme_colours
fi
